name: Merge on main
on:
  pull_request:
    branches:
      - main
    types: [ closed ]

steps:
  # Checkout code
  - name: Checkout Code
    uses: actions/checkout@v2
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      fetch-depth: 0

  - name: Configure NPM Token
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    run: |
      yarn config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
      ./.github/scripts/publish-libraries.sh

  - name: Generate changelog and bump versions
    run: |
      git config --local user.email "automation@softkit.dev"
      git config --local user.name "GitHub Auto Release"
      nx affected --target version --push --skipRootChangelog true --base=last-release --changelogHeader "Softkit Core Libraries Changelog" --trackDeps --parallel=false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  - name: Tag last-release
    run: |
      git tag -a last-release -m "Last release"
      git push origin last-release --force
