services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.docker-data/postgres-db:/var/lib/postgresql/data
      - ./init-extensions-db.sh:/docker-entrypoint-initdb.d/init-extensions-db.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local-db

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-main}"
    image: localstack/localstack:3.0.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./docker-data/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  cache:
    image: redis/redis-stack:7.2.0-v2
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./.docker-data/redis-db:/data
volumes:
  cache:
    driver: local
