name: Merge on main
on:
  pull_request:
    branches:
      - main
    types: [ closed ]


jobs:
  publish:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest node only
        node-version: [ 20.x ]
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install environment
        run: yarn install

      - name: Configure NPM Token
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > .npmrc

      - name: Generate changelog and bump versions
        run: |
          git config --local user.email "automation@softkit.dev"
          git config --local user.name "GitHub Auto Release"
          git remote set-url origin "https://vsamofal:${PERSONAL_GITHUB_TOKEN}@github.com/saas-buildkit/saas-buildkit-core/"
          git remote -v
          npx nx affected --noVerify --target version --push --skipRootChangelog true --base=last-release --changelogHeader "Softkit Core Libraries Changelog" --trackDeps --parallel=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Tag last-release
        run: |
          git tag -a last-release -m "Last release"
          git push origin last-release --force
